### ISSUE TITLE
lorri Crash Report

### ISSUE THREAD

**Issue by tbehner** [nix-community/lorri#119]
name = 'lorri'
operating_system = 'unix:Unknown'
crate_version = '1.6.0'
explanation = '''
Panic occurred in file 'src/build_loop.rs' at line 238
'''
cause = '''
Unrecoverable error:
Io {
    msg: "AddRootError { source: Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }, msg: \"Failed to create missing nix user gc directory: /nix/var/nix/gcroots/per-user/coffeemaster\" }",
}'''
method = 'Panic'
backtrace = '''

   0: 0x55fd311d950f - lorri::build_loop::BuildLoop::forever::hb6c0f32cbf8ea65a
   1: 0x55fd3122ff2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h5929e3776d10ad02
   2: 0x55fd312438b2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbe6828f778dbb144
   3: 0x55fd313d3615 - std::sys::unix::thread::Thread::new::thread_start::hd89eec8fc730285b
   4: 0x7fa9594670e4 - start_thread
   5: 0x7fa9594e975c - __GI___clone3
   6:        0x0 - <unresolved>'''

**Comment by tbehner** [comment]
The operating system is NixOS 23.11, and I installed lorri in the nixos configuration.

**Comment by nyarly** [comment]
We're in the process of a release that will fix this issue. If you want to use the lorri 1.7.0 release, you can update your Nix config to pull from the repo directly. Otherwise, hang tight for a release in nixpkgs.

Alternatively, there's a workaround for 1.6.0 that involves creating the gc-roots directory (i.e. `/nix/var/nix/gcroots/per-user/coffeemaster`) as root, and setting it to be writable by your user.

**Comment by nyarly** [comment]
This bug is fixed in 1.7.0, which is in nixpkgs as of NixOS 24.05. Thank you for your patience!
